name: CI Debug Pipeline

on:
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - run: node --version
      - run: npm --version

      # install
      - run: npm install

      # show structure (VERY IMPORTANT)
      - run: ls -R

      # run lint separately (to isolate error)
      - run: npx htmlhint "src/*.html"
        continue-on-error: true

      - run: npx stylelint "styles/style.css"
        continue-on-error: true

      # build step with full error visibility
      - run: npx parcel build src/index.html --dist-dir dist